# Generated by Django 5.0.1 on 2024-01-26 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='option',
            name='link_de',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='option',
            name='link_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='option',
            name='link_fr',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='option',
            name='link_uk',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='option',
            name='name_de',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='option',
            name='name_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='option',
            name='name_fr',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='option',
            name='name_uk',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
