# Generated by Django 5.0.1 on 2024-01-26 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0002_option_link_de_option_link_en_option_link_fr_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='extraoption',
            name='link_de',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='extraoption',
            name='link_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='extraoption',
            name='link_fr',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='extraoption',
            name='link_uk',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='extraoption',
            name='name_de',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='extraoption',
            name='name_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='extraoption',
            name='name_fr',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='extraoption',
            name='name_uk',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
