# Generated by Django 5.0.1 on 2024-01-31 10:54

import django.db.models.deletion
import mptt.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0003_extraoption_link_de_extraoption_link_en_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='option',
            name='extraOptions',
        ),
        migrations.AddField(
            model_name='option',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='mainApp.option'),
        ),
        migrations.DeleteModel(
            name='ExtraOption',
        ),
    ]
